# Generated by Django 4.2.5 on 2023-12-12 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('Nombre', models.CharField(blank=True, default='', max_length=100)),
                ('Telefono', models.CharField(blank=True, default='', max_length=100)),
                ('Cantidad', models.CharField(blank=True, default='', max_length=100)),
                ('tipo_usuario', models.CharField(blank=True, default='', max_length=1)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('Cantidad', models.CharField(blank=True, default='', max_length=100)),
                ('Precio_unitario', models.CharField(blank=True, default='', max_length=100)),
                ('Fecha', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
        ),
    ]
